# Generated by Django 2.0.6 on 2018-06-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.TextField(),
        ),
    ]
