# Generated by Django 2.0.6 on 2018-06-02 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0002_auto_20180602_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='documen_type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesis.DocumentType'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='format',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
