# Generated by Django 2.0.6 on 2018-06-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0003_auto_20180602_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.TextField(),
        ),
    ]
