# Generated by Django 2.0.6 on 2018-06-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0004_auto_20180602_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
