# Generated by Django 2.0.6 on 2018-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0006_full_searches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searches',
            name='word',
            field=models.TextField(),
        ),
    ]
