# Generated by Django 2.0.6 on 2018-06-03 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0008_auto_20180603_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesis',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 3, 10, 12, 35, 320898)),
        ),
    ]
