# Generated by Django 2.0.6 on 2018-06-03 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0010_auto_20180603_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 10, 15, 9, 409548)),
        ),
    ]
