# Generated by Django 2.0.6 on 2018-06-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0013_auto_20180611_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesisranking',
            name='user_email',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='tesisranking',
            unique_together={('tesis_id', 'user_email')},
        ),
    ]
